name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.0"
          rebar3-version: "3"

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.42.0

      - name: Test
        run: task test

      - name: Check format
        run: gleam format --check
